name: Deploy New Version

permissions: write-all

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "mykitchenpower"
        heroku_email: "ibadiela@gmail.com"

   